version: "3.9"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - ./config:/config
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      - TZ=Asia/Bangkok

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./ha-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ha-config/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - homeassistant
    restart: unless-stopped

  # Django Backend Service
  backend:
    container_name: django_backend
    build:
      context: ./djago
      dockerfile: Dockerfile
    volumes:
      - ./djago:/app
    ports:
      - "8000:8000"
    depends_on:
      - homeassistant
    restart: unless-stopped
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  # React Frontend Service
  frontend:
    container_name: react_frontend
    build:
      context: ./frontend  # ตรวจสอบว่าชี้ไปที่โฟลเดอร์ frontend จริงๆ
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app  # เพิ่ม volume เพื่อให้โค้ดอัปเดตได้อัตโนมัติ
      - /app/node_modules  # ป้องกันปัญหาการ build ซ้ำ
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
